In [1]:
import sympy as smp
from sympy import symbols,diff
import numpy as np
import math
from datetime import datetime

## bisection method

In [2]:
def f(x):
    return x**3-3*x+5
for u in range(-5,0):
    for v in range(-5,5):
        if abs(u-v)==1 and f(u)*f(v)<0:
            a=u
            b=v
print(a,b)
# a=int(input('Enter start point of interval:\n'))
# b=int(input('Enter end point of interval:\n'))
# z=int(input('Enter the required significant points:\n'))

a = -3  # Start point of the interval
b = -2  # End point of the interval
z = 3  
e=10**(-z)
i=math.ceil(math.log(abs(b-a)/e,2))
if f(a)*f(b)>0:
    print(f"Bisection fails in the interval [{a},{b}]")
print("number of iterations:",i)
t_i= datetime.now()
n=0
while n<i:
    mid=(a+b)/2
    err=abs(b-a)
    print(f'at iteration {i} approximate root is mid and error is {err}')

    if f(a)*f(mid)<0:
        b=mid
    elif f(mid)*f(b)<0:
        a=mid
    print(f"iteration {n}",mid)
    n+=1
t_f= datetime.now()
print("cost of computtation:",t_f-t_i)

-2 -3
number of iterations: 10
at iteration 10 approximate root is mid and error is 1
iteration 0 -2.5
at iteration 10 approximate root is mid and error is 0.5
iteration 1 -2.25
at iteration 10 approximate root is mid and error is 0.25
iteration 2 -2.375
at iteration 10 approximate root is mid and error is 0.125
iteration 3 -2.3125
at iteration 10 approximate root is mid and error is 0.0625
iteration 4 -2.28125
at iteration 10 approximate root is mid and error is 0.03125
iteration 5 -2.265625
at iteration 10 approximate root is mid and error is 0.015625
iteration 6 -2.2734375
at iteration 10 approximate root is mid and error is 0.0078125
iteration 7 -2.27734375
at iteration 10 approximate root is mid and error is 0.00390625
iteration 8 -2.279296875
at iteration 10 approximate root is mid and error is 0.001953125
iteration 9 -2.2783203125
cost of computtation: 0:00:00


## Newton Raphson

'''the difference in the use of library change the number of iteration required for the results.
Lambdify library considers the integer value of the derivative which reduces the number 
of iterations
 whereas subs command takes float value to find accurate results, increasing 
 the number of iterations.'''

In [3]:
# x0=int(input('enter initial value:\n'))
# z=int(input('enter tolerance:\n'))
x0 = -2  # Initial guess
z = 4 
e=10**(-z)
x=symbols('x')
def f(x):
    return x**3-3*x+5
itime=datetime.now()
dfdx=diff(f(x),x)
dfdx_val=smp.lambdify(x,dfdx)
if dfdx_val(x0)!=0:
    h=((f(x0))/dfdx_val(x0))
    i=0
    while abs(h)>=e:
        h=((f(x0))/dfdx_val(x0))
        x1=x0-h
        print(f'iteration {i+1}',x1)
        x0=x1
        i+=1
    ftime=datetime.now()
    print(f'The root of {f(x)} is :',x1)
    print("cost of computation",ftime-itime)

iteration 1 -2.3333333333333335
iteration 2 -2.2805555555555554
iteration 3 -2.2790200679500896
iteration 4 -2.2790187861674864
The root of x**3 - 3*x + 5 is : -2.2790187861674864
cost of computation 0:00:00.169319


## Newton Raphson with multiplicity

In [6]:
x0 = 3   # Initial guess  
z = 4    # Tolerance (4 significant digits)  
m = 2

e=10**(-z)
x=symbols('x')
def f(x):
    return x**2-1
dfdx=diff(f(x),x)
dfdx_val=smp.lambdify(x,dfdx)
if dfdx_val(x0)!=0:
    h=((f(x0))/dfdx_val(x0))
    i=0
    while abs(h)<=e:
        if dfdx_val(x0)!=0:
            h=((f(x0))/(dfdx_val(x0)))
            x1=x0-m*h
            print(f'iteration {i+1}',x1)
            x0=x1
        i+=1
    print(f'The root of {f(x)} is :',x1)

The root of x**2 - 1 is : 0.33333333333333304


## Newton Raphson without multiplicity


In [8]:
# x0=int(input('enter initial value:\n'))
# z=int(input('enter tolerance:\n'))

x0 = 3   # Initial guess  
z = 4 
e=10**(-z)
x=symbols('x')
def f(x):
    return x**2-1
dfdx=diff(f(x),x)
dfdx_val=smp.lambdify(x,dfdx)
if dfdx_val(x0)!=0:
    h=((f(x0))/dfdx_val(x0))
    i=0
    while abs(h)>=e:
        if dfdx_val(x0)!=0:
            g=f(x)/dfdx
            dgdx=diff(g,x)
            dgdx_val=smp.lambdify(x,dgdx)
            h=((f(x0))/(dfdx_val(x0)*dgdx_val(x0)))
            x1=x0-h
            print(f'iteration {i+1}',x1)
            x0=x1
        i+=1
    print(f'The root of {f(x)} is :',x1)

iteration 1 0.6000000000000001
iteration 2 0.8823529411764706
iteration 3 0.9922178988326849
iteration 4 0.9999694828875292
iteration 5 0.9999999995343387
The root of x**2 - 1 is : 0.9999999995343387


## Regula-Falsi

In [9]:
# a=int(input('enter starting interval:\n'))
# b=int(input('enter ending interval:\n'))
# z=int(input('enter required significant digits:\n'))
a = -3   # Starting interval  
b = -2   # Ending interval  
z = 4
e=10**(-z)
def f(x):
    return x**3-3*x+5
itime=datetime.now()
i=1
while i>e:

    p= (a*f(b)-b*f(a))/(f(b)-f(a))
    i=abs(p-b)
    print(f'for approximate root p the error is {i}')
    if f(a)*f(p)<0:
        b=p
    elif f(p)*f(b)<0:
        a=p
    ftime=datetime.now()
    print(f"iteration {z}",p)
print("cost of computation",ftime-itime)

for approximate root p the error is 0.1875
iteration 4 -2.1875
for approximate root p the error is 0.06311922990317509
iteration 4 -2.250619229903175
for approximate root p the error is 0.019746460771659535
iteration 4 -2.2703656906748346
for approximate root p the error is 0.006031510908789617
iteration 4 -2.2763972015836242
for approximate root p the error is 0.0018287106533447783
iteration 4 -2.278225912236969
for approximate root p the error is 0.0005532023634646777
iteration 4 -2.2787791146004337
for approximate root p the error is 0.0001672346480194875
iteration 4 -2.278946349248453
for approximate root p the error is 5.0545062238338545e-05
iteration 4 -2.2789968943106915
cost of computation 0:00:00


## secant method

In [10]:
# a=int(input('enter starting interval:\n'))
# b=int(input('enter ending interval:\n'))
# z=int(input('enter required significant digits:\n'))

a = -3   # Starting interval  
b = -2   # Ending interval  
z = 4
e=10**(-z)
def f(x):
    return x**3-3*x+5
itime=datetime.now()
z=1
while z>e and (f(b)-f(a))!=0:
    p= b - (f(b)*((b-a)/(f(b)-f(a))))
    err = abs(p-b)
    print(f'for approximate root p the error is {err}')
    print(p)
    a=b
    b=p
ftime=datetime.now()
print("cost of computation",ftime-itime)

for approximate root p the error is 0.1875
-2.1875
for approximate root p the error is 0.1077710495963089
-2.295271049596309
for approximate root p the error is 0.01708522065639073
-2.278185828939918
for approximate root p the error is 0.0008256456745545648
-2.2790114746144727
for approximate root p the error is 7.314862702667568e-06
-2.2790187894771754
for approximate root p the error is 3.3105949093226172e-09
-2.2790187861665805
for approximate root p the error is 1.2878587085651816e-14
-2.2790187861665934
for approximate root p the error is 0.0
-2.2790187861665934
cost of computation 0:00:00.000541


## Newton Non- linear

In [13]:
import numpy as np
import sympy as smp
from sympy import symbols, diff

x, y = symbols('x y')

# Define equations
u = (x**3) - (3*x*(y**2)) + 1
v = -y**3 + (3*x**2)*y

# Compute derivatives for the Jacobian
dudx = smp.lambdify([x, y], diff(u, x))
dudy = smp.lambdify([x, y], diff(u, y))
dvdx = smp.lambdify([x, y], diff(v, x))
dvdy = smp.lambdify([x, y], diff(v, y))
u_val = smp.lambdify([x, y], u)
v_val = smp.lambdify([x, y], v)


x0 = 1
y0 = 1
n = 10  

for i in range(n):
    J = np.array([[dudx(x0, y0), dudy(x0, y0)], [dvdx(x0, y0), dvdy(x0, y0)]])
    P = np.array([u_val(x0, y0), v_val(x0, y0)])


    inv_J = np.linalg.inv(J)
    ans = np.dot(inv_J, -P)
    
    x0 += ans[0]
    y0 += ans[1]
    
    print(f"Iteration {i+1}: x = {x0}, y = {y0}")

n = 5
k = 0.005125
h = 0.1
s = float(k / h**2)

A = np.zeros((n, n), dtype=float)

for i in range(n):
    for j in range(n):
        if i == j:
            A[i, j] = 1 - 2 * s  
        if i + 1 < n:
            A[i + 1, j] = s  
        if i - 1 >= 0:
            A[i - 1, j] = s 

print("Matrix A:\n", A)


Iteration 1: x = 0.6666666666666667, y = 0.8333333333333334
Iteration 2: x = 0.5086919161874546, y = 0.8410998744133783
Iteration 3: x = 0.4993299956437513, y = 0.8662691717880057
Iteration 4: x = 0.4999999113699129, y = 0.8660249031568892
Iteration 5: x = 0.4999999999999554, y = 0.8660254037846933
Iteration 6: x = 0.49999999999999994, y = 0.8660254037844386
Iteration 7: x = 0.5, y = 0.8660254037844386
Iteration 8: x = 0.5, y = 0.8660254037844387
Iteration 9: x = 0.5, y = 0.8660254037844386
Iteration 10: x = 0.5, y = 0.8660254037844387
Matrix A:
 [[ 0.5125  0.5125  0.5125  0.5125  0.5125]
 [ 0.5125  0.5125  0.5125  0.5125  0.5125]
 [ 0.5125  0.5125  0.5125  0.5125  0.5125]
 [ 0.5125  0.5125  0.5125  0.5125  0.5125]
 [ 0.5125  0.5125  0.5125  0.5125 -0.025 ]]
