## Gauss Jacobi iterative

In [2]:
import numpy as np
import time


A=np.array([[15,3,-2],[2,10,1],[1,-2,8]],dtype=np.float64)
B=np.array([[85],[51],[5]],dtype=np.float64)
L=np.empty([len(A),len(A)])
U=np.empty([len(A),len(A)])
D=np.empty([len(A),len(A)])
t_i=time.time()

for i in range(len(A)):
    
    for j in range(len(A)):
        if i>j:
            L[i][j]=A[i][j]
        elif i<j:
            U[i][j]=A[i][j]
        elif (i==j):
            D[i][j]=A[i][j]
        else:
            L[i][j]=0
            U[i][j]=0
            D[i][j]=0
# print("D\n",D)
H=-np.dot(np.linalg.inv(D),(L+U))
C=np.dot(np.linalg.inv(D),B)
# print("H\n",H)
# print("C\n",C)
x0=np.array([[0],[0],[0]])
i=0
n=20
while i<n:
    x1=np.dot(H,x0)+C
    print(f'\niteration {i+1}:\n',x1)
    x0=x1
    i+=1
t_f=time.time()
print('\ncost of computation:',t_f-t_i)


iteration 1:
 [[5.66666667]
 [5.1       ]
 [0.625     ]]

iteration 2:
 [[-1.87333333]
 [-1.25833333]
 [ 0.56666667]]

iteration 3:
 [[ 8.19444444]
 [ 6.61966667]
 [-0.02208333]]

iteration 4:
 [[-5.18153333]
 [-3.15413889]
 [ 1.27769444]]

iteration 5:
 [[12.45057407]
 [ 9.03490667]
 [-0.7935375 ]]

iteration 6:
 [[-10.60948007]
 [ -6.26631398]
 [  2.12094241]]

iteration 7:
 [[19.34825698]
 [13.06402151]
 [-1.73633589]]

iteration 8:
 [[-19.37022182]
 [-11.48640573]
 [  3.20880915]]

iteration 9:
 [[30.48713322]
 [19.81868827]
 [-3.03413286]]

iteration 10:
 [[-33.55704395]
 [-20.20928834]
 [  4.80291327]]

iteration 11:
 [[48.58820283]
 [31.06011447]
 [-5.03560486]]

iteration 12:
 [[-56.68840991]
 [-34.67063407]
 [  7.35210813]]

iteration 13:
 [[78.18389237]
 [49.63789443]
 [-8.3087154 ]]

iteration 14:
 [[-94.58804092]
 [-58.51292982]
 [ 11.57020246]]

iteration 15:
 [[126.74526683]
 [ 80.21649751]
 [-13.7499298 ]]

iteration 16:
 [[-156.83184712]
 [ -97.71556492]
 [  18.5858958

## Gauss seidel iterative

In [3]:
A=np.array([[15,3,-2],[2,10,1],[1,-2,8]],dtype=np.float64)
B=np.array([[85],[51],[5]],dtype=np.float64)
L=np.empty([len(A),len(A)])
U=np.empty([len(A),len(A)])
D=np.empty([len(A),len(A)])
t_i=time.time()

for i in range(len(A)):
    for j in range(len(A)):
        if i>j:
            L[i][j]=A[i][j]
        elif i<j:
            U[i][j]=A[i][j]
        elif (i==j):
            D[i][j]=A[i][j]
        else:
            L[i][j]=0
            U[i][j]=0
            D[i][j]=0
# print("D\n",D)
H=-np.dot(np.linalg.inv(L+D),U)
C=np.dot(np.linalg.inv(L+D),B)
# print("H\n",H)
# print("C\n",C)
x0=np.array([[0],[0],[0]])
i=0
n=20
while i<n:
    x1=np.dot(H,x0)+C
    print(f'\niteration {i+1}:\n',x1)
    x0=x1
    i+=1
t_f=time.time()
print('\ncost of computation:',t_f-t_i)


iteration 1:
 [[2.4400166 ]
 [2.26172686]
 [0.44271482]]

iteration 2:
 [[1.2522374 ]
 [1.00095424]
 [0.26821185]]

iteration 3:
 [[1.82891262]
 [1.6957068 ]
 [0.32290483]]

iteration 4:
 [[1.54972171]
 [1.31649708]
 [0.31640843]]

iteration 5:
 [[1.68447975]
 [1.52181616]
 [0.30694735]]

iteration 6:
 [[1.61964838]
 [1.41141453]
 [0.31917215]]

iteration 7:
 [[1.65072742]
 [1.47042205]
 [0.30874501]]

iteration 8:
 [[1.63588674]
 [1.43905049]
 [0.31639818]]

iteration 9:
 [[1.64294288]
 [1.45565071]
 [0.31121171]]

iteration 10:
 [[1.63960406]
 [1.44690394]
 [0.31455429]]

iteration 11:
 [[1.6411754 ]
 [1.45149497]
 [0.312474  ]]

iteration 12:
 [[1.64044041]
 [1.44909367]
 [0.31373559]]

iteration 13:
 [[1.64078178]
 [1.45034559]
 [0.31298573]]

iteration 14:
 [[1.64062454]
 [1.44969486]
 [0.3134243 ]]

iteration 15:
 [[1.64069626]
 [1.45003216]
 [0.31317118]]

iteration 16:
 [[1.64066393]
 [1.44985778]
 [0.31331564]]

iteration 17:
 [[1.64067829]
 [1.44994771]
 [0.31323398]]

itera

## Power Method

In [4]:
A=np.array([[-15,4,3],[10,-12,6],[20,-4,2]],dtype=np.float64)
x=np.array([[1],[1],[1]],dtype=np.float64)
z=5
e=10**(-z)
p=1
while p>e:
    b1=np.dot(A,x)
    lam1=max(b1)
    x=b1/lam1
    b2=np.dot(A,x)
    lam2=max(b2)
    p=abs(lam2-lam1)
print(lam2)

[19.99999046]
