## Euler's method

In [1]:
import numpy as np
import sympy as smp
from sympy import symbols,diff
from datetime import datetime as dt

In [2]:
x=symbols('x')
y=symbols('y')

dydx=x**2+y**2
dydx_val=smp.lambdify([x,y],dydx)

# h=float(input('enter step size:\n'))
# start_range=float(input('enter the starting point of range:\n'))
# end_range=float(input('enter the end point of range:\n'))
# val=float(input("enter the value of x to evaluate \n"))

h=0.05
end_range=0.2
start_range=0
val=0.2
n=int((float(end_range)-float(start_range))/h)
y=np.empty(n+1)
x=np.empty(n+1)
x[0]=0
y[0]=1
i=0
while i<n:
    y[i+1]=y[i]+h*dydx_val(x[i],y[i])
    x[i+1]=x[i]+h
    i+=1
print('x=',x)
print('y=',y)

x= [0.   0.05 0.1  0.15 0.2 ]
y= [1.         1.05       1.10525    1.16682888 1.23602836]


## RK method 2nd order

In [ ]:
x=symbols('x')
y=symbols('y')
dydx=y**2-x**2
fx=smp.lambdify([x,y],dydx)
k=2

# x0=float(input('enter the initial value of x:\n'))
# y0=float(input('enter the initial value of y:\n'))
# h=float(input('enter the step size:\n'))
# pt=float(input("enter the point of iteration:\n"))

x0 = 0.0       # Initial value of x
y0 = 1.0       # Initial value of y
h = 0.1        
pt = 0.5

n=int(abs((pt-x0)/h))
iter=np.zeros([n,2+k+1])
for i in range(n):
    iter[i][0]=x0
    iter[i][1]=y0
    iter[i][2]=h*fx(iter[i][0],iter[i][1])
    iter[i][3]=h*fx(iter[i][0]+h,iter[i][1]+iter[i][2])
    iter[i][4]=y0+(1/2)*(iter[i][2]+iter[i][3])
    x0+=h
    y0=iter[i][4]
print(iter)

[[0.         1.         0.1        0.12       1.11      ]
 [0.1        1.11       0.12221    0.14783415 1.24502207]
 [0.2        1.24502207 0.151008   0.18589    1.41347107]
 [0.3        1.41347107 0.19079005 0.24136537 1.62954878]
 [0.4        1.62954878 0.24954292 0.32809856 1.91836952]]


## simplified rk2

In [10]:
x=symbols('x')
y=symbols('y')
dydx=y**2-x**2
fx=smp.lambdify([x,y],dydx)

# x0=float(input('enter the initial value of x:\n'))
# y0=float(input('enter the initial value of y:\n'))
# h=float(input('enter the step size:\n'))
# pt=float(input("enter the point of iteration:\n"))

x0 = 0.0       # Initial value of x
y0 = 1.0       # Initial value of y
h = 0.1        
pt = 0.5

n=int(abs((pt-x0)/h))
t_i=dt.now()
for i in range(n):
    k1=h*fx(x0,y0)
    k2=h*fx(x0+h,y0+k1)
    y1=y0+(1/2)*(k1+k2)
    print(f"y({x0+h}) is {y1}")
    x0=x0+h
    y0=y1   
t_f=dt.now()
print("cost",t_f-t_i)

y(0.1) is 1.11
y(0.2) is 1.245022074205
y(0.30000000000000004) is 1.4134710703871143
y(0.4) is 1.6295487803151918
y(0.5) is 1.9183695231115736
cost 0:00:00


## RK method 4th order

In [12]:
x=symbols('x')
y=symbols('y')
dydx=y**2+x**2
fx=smp.lambdify([x,y],dydx)
k=4

# x0=float(input('enter the initial value of x:\n'))
# y0=float(input('enter the initial value of y:\n'))
# h=float(input('enter the step size:\n'))
# pt=float(input("enter the point of iteration:\n"))

x0 = 0.0   # Initial value of x
y0 = 1.0   # Initial value of y
h = 0.1    # Step size
pt = 0.5 

n=int(abs((pt-x0)/h))
iter=np.zeros([n,2+k+1])
t_i=dt.now()
for i in range(n):
    iter[i][0]=x0
    iter[i][1]=y0
    iter[i][2]=h*fx(iter[i][0],iter[i][1])
    iter[i][3]=h*fx(iter[i][0]+h/2,iter[i][1]+iter[i][2]/2)
    iter[i][4]=h*fx(iter[i][0]+h/2,iter[i][1]+iter[i][3]/2)
    iter[i][5]=h*fx(iter[i][0]+h,iter[i][1]+iter[i][4])
    iter[i][6]=y0+(1/6)*(iter[i][2]+2*iter[i][3]+2*iter[i][4]+iter[i][5])
    x0=x0+h
    y0=iter[i][6]
t_f=dt.now()
print("cost",t_f-t_i)
print(iter)

cost 0:00:00.005632
[[0.         1.         0.1        0.1105     0.11160526 0.12456662
  1.11146286]
 [0.1        1.11146286 0.12453497 0.14001429 0.14183714 0.16107609
  1.25301517]
 [0.2        1.25301517 0.1610047  0.1840769  0.18716693 0.21641245
  1.43966597]
 [0.3        1.43966597 0.21626381 0.25181783 0.25735247 0.30398716
  1.6960979 ]
 [0.4        1.6960979  0.30367481 0.36173649 0.37255019 0.45293049
  2.06696102]]


## simplified rk4

In [13]:
x=symbols('x')
y=symbols('y')
dydx=y**2+x**2
fx=smp.lambdify([x,y],dydx)
# x0=float(input('enter the initial value of x:\n'))
# y0=float(input('enter the initial value of y:\n'))
# h=float(input('enter the step size:\n'))
# pt=float(input("enter the point of iteration:\n"))

x0 = 0.0   # Initial x value
y0 = 1.0   # Initial y value
h = 0.1    # Step size
pt = 0.5

n=int(abs((pt-x0)/h))
t_i=dt.now()
for i in range(n):
    k1=h*fx(x0,y0)
    k2=h*fx(x0+h/2,y0+k1/2)
    k3=h*fx(x0+h/2,y0+k2/2)
    k4=h*fx(x0+h,y0+k3)
    y1=y0+(1/6)*(k1+2*k2+2*k3+k4)
    print(f"y({x0+h}) is {y1}")
    x0=x0+h
    y0=y1   
t_f=dt.now()
print("cost",t_f-t_i)

y(0.1) is 1.1114628561787105
y(0.2) is 1.2530151746035345
y(0.30000000000000004) is 1.439665974547582
y(0.4) is 1.696097903722817
y(0.5) is 2.066961015450312
cost 0:00:00


## Adams Bashforth

In [15]:
def rk4(x0,y0,h,pt):
    n=int(abs((pt-x0)/h))
    iter=np.zeros([n,2])
    for i in range(n):
        iter[i][0]=x0
        iter[i][1]=y0
        k1=h*fx(x0,y0)
        k2=h*fx(x0+h/2,y0+k1/2)
        k3=h*fx(x0+h/2,y0+k2/2)
        k4=h*fx(x0+h,y0+k3)
        y1=y0+(1/6)*(k1+2*k2+2*k3+k4)
        # iter[i][2]=y1
        x0=x0+h
        y0=y1 
    return iter

x=symbols('x')
y=symbols('y')
dydx=2*y-y**2
fx=smp.lambdify([x,y],dydx)
k=4
# x0=float(input('enter the initial value of x:\n'))
# y0=float(input('enter the initial value of y:\n'))
# h=float(input('enter the step size:\n'))
# pt=float(input("enter the point of iteration:\n"))
x0=0
y0=1
h=0.05
pt=0.2
gx=rk4(x0,y0,h,pt)
x1=gx[1][0]
x2=gx[2][0]
x3=gx[3][0]
y1=gx[1][1]
y2=gx[2][1]
y3=gx[3][1]
# z=int(input("enter number of point of iteration:\n"))
z=2
for i in range(z):
    x4=x3+h
    yp4= y3+ (h/24)*(-9*fx(x0,y0)+37*fx(x1,y1)-59*fx(x2,y2)+55*fx(x3,y3))
    yc4= y3+ (h/24)*(fx(x1,y1)-5*fx(x2,y2)+19*fx(x3,y3)+9*fx(x4,yp4))
    print(f"yp={yp4}")
    print(f"yc={yc4}")
    x0=x1
    x1=x2
    x2=x3
    x3=x4
    y0=y1
    y1=y2
    y2=y3
    y3=yc4

yp=1.1973737160069717
yc=1.1973754358841606
yp=1.2449173425537745
yc=1.2449188844523427


## Milne method

In [17]:
x=symbols('x')
y=symbols('y')
dydx=2*y-(y**2)
fx=smp.lambdify([x,y],dydx)
k=4
# x0=float(input('enter the initial value of x:\n'))
# y0=float(input('enter the initial value of y:\n'))
# h=float(input('enter the step size:\n'))
# pt=float(input("enter the point of iteration:\n"))
x0=0
y0=1
h=0.05
pt=0.2
def rk4(x0,y0,h,pt):
    n=int(abs((pt-x0)/h))
    iter=np.zeros([n,2])
    for i in range(n):
        iter[i][0]=x0
        iter[i][1]=y0
        k1=h*fx(x0,y0)
        k2=h*fx(x0+h/2,y0+k1/2)
        k3=h*fx(x0+h/2,y0+k2/2)
        k4=h*fx(x0+h,y0+k3)
        y1=y0+(1/6)*(k1+2*k2+2*k3+k4)
        x0=x0+h
        y0=y1 
    return iter
gx=rk4(x0,y0,h,pt)
print(rk4(x0,y0,h,pt))
x1=gx[1][0]
x2=gx[2][0]
x3=gx[3][0]
y1=gx[1][1]
y2=gx[2][1]
y3=gx[3][1]
# z=int(input("enter number of point of iteration:\n"))
z=2
for i in range(z):
    x4=x3+h
    yp4= y0+ (4*h/3)*(2*fx(x1,y1)-fx(x2,y2)+2*fx(x3,y3))
    yc4= y2+ (h/3)*(fx(x2,y2)+4*fx(x3,y3)+fx(x4,yp4))
    print(f"yp={yp4}")
    print(f"yc={yc4}")
    x0=x1
    x1=x2
    x2=x3
    x3=x4
    y0=y1
    y1=y2
    y2=y3
    y3=yc4

[[0.         1.        ]
 [0.05       1.04995837]
 [0.1        1.09966799]
 [0.15       1.14888503]]
yp=1.1973739019016172
yc=1.1973753698662124
yp=1.2449173897751795
yc=1.2449187017523928
