In [1]:
import numpy as np
import sympy as smp
from sympy import symbols, Eq, solve, simplify
import math
from datetime import datetime
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import time

## newton forward difference

In [2]:
x=np.array([1891,1901,1911,1921,1931])
y=np.array([46,66,81,93,101])
# n= int(input('Enter the number of data points:\n'))
# p=float(input('Enter the evaluation point of data:\n'))
# x=np.empty(n)
# x[0]=int(input("enter initial data point:\n"))
n=len(x)
h=10
p=1895
# u=(p-x0)/h 
u=symbols('u')
rslt = np.zeros([n,n+1])
for k in range(n):
    rslt[k][0]=x[k]
    rslt[k][1]=y[k]
print('Initializing the resultant matrix:\n',rslt,'\n')
a=n-1
j=2
while j<n+2:
    i=0
    while i<a:
        rslt[i][j]=((rslt[i+1][j-1]-rslt[i][j-1]))
        i+=1
    a-=1
    j+=1
print('The resultant matrix is:\n',rslt,'\n')
j=2
sum=rslt[0][1]
while j<n+1:
    partition=rslt[0][j]
    k=0
    while k<j-1:
        partition = partition* (u-(k))
        k+=1
    # print(partition)
    sum+=partition/math.factorial(j-1)
    j+=1
print(f'The polynomial is:\n',sum,'\n')
poly=smp.lambdify(u,sum)
print(f"The simplified value of the polynomial is:\n",simplify(sum),'\n')
u = (p-x[0])/h
print(f'The value of polynomial at {p} is:\n',poly(u),'\n')


Initializing the resultant matrix:
 [[1891.   46.    0.    0.    0.    0.]
 [1901.   66.    0.    0.    0.    0.]
 [1911.   81.    0.    0.    0.    0.]
 [1921.   93.    0.    0.    0.    0.]
 [1931.  101.    0.    0.    0.    0.]] 

The resultant matrix is:
 [[ 1.891e+03  4.600e+01  2.000e+01 -5.000e+00  2.000e+00 -3.000e+00]
 [ 1.901e+03  6.600e+01  1.500e+01 -3.000e+00 -1.000e+00  0.000e+00]
 [ 1.911e+03  8.100e+01  1.200e+01 -4.000e+00  0.000e+00  0.000e+00]
 [ 1.921e+03  9.300e+01  8.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 1.931e+03  1.010e+02  0.000e+00  0.000e+00  0.000e+00  0.000e+00]] 

The polynomial is:
 -0.125*u*(u - 3)*(u - 2)*(u - 1) + 0.333333333333333*u*(u - 2)*(u - 1) - 2.5*u*(u - 1) + 20.0*u + 46.0 

The simplified value of the polynomial is:
 -0.125*u**4 + 1.08333333333333*u**3 - 4.875*u**2 + 23.9166666666667*u + 46.0 

The value of polynomial at 1895 is:
 54.8528 



## newton backward difference

In [3]:
x=np.array([0,1,2,3,4])
y=np.array([5,8,12,17,26])
p=4
n=len(x)
# rslt = np.zeros([n,n+2])
# for k in range(n):
#     rslt[k][0]=rslt[k][0]+x[k]
#     rslt[k][1]=rslt[k][1]+y[k]

# n= int(input('Enter the number of data points:\n'))
# p=float(input('Enter the evaluation point of data:\n'))
# x[0]=int(input("enter initial data point:\n"))
h=1
u=(p-x[0])/h 
u=symbols('u')
rslt = np.zeros([n,n+2])
for k in range(n):
    rslt[k][0]=x[k]
    # rslt[k][1]=input('Enter the functional value at given point x:\n')
    rslt[k][1]=y[k]
print('Initializing the resultant matrix:\n',rslt,'\n')

j=2
while j<n+2:
    a=j-1
    i=n-1
    while i>a-1:
        rslt[i][j]=((rslt[i][j-1]-rslt[i-1][j-1]))
        i-=1
    a-=1
    j+=1
print('The resultant matrix is:\n',rslt,'\n')
j=2
sum=rslt[n-1][1]
while j<n:
    partition=rslt[n-1][j]
    k=0
    while k<j-1:
    # for k in range(j-1):
        partition = partition* (u+(k))
        k+=1
    # print(partition)
    sum+=partition/math.factorial(j-1)
    j+=1
print(f'The polynomial is:\n',sum,'\n')
poly=smp.lambdify(u,sum)
print(f"The simplified value of the polynomial is:\n",simplify(sum),'\n')
u = (p-rslt[n-1][0])/h
# print(u)
print(f'The value of polynomial at {p} is:\n',poly(p),'\n')

Initializing the resultant matrix:
 [[ 0.  5.  0.  0.  0.  0.  0.]
 [ 1.  8.  0.  0.  0.  0.  0.]
 [ 2. 12.  0.  0.  0.  0.  0.]
 [ 3. 17.  0.  0.  0.  0.  0.]
 [ 4. 26.  0.  0.  0.  0.  0.]] 

The resultant matrix is:
 [[ 0.  5.  0.  0.  0.  0.  0.]
 [ 1.  8.  3.  0.  0.  0.  0.]
 [ 2. 12.  4.  1.  0.  0.  0.]
 [ 3. 17.  5.  1.  0.  0.  0.]
 [ 4. 26.  9.  4.  3.  3.  0.]] 

The polynomial is:
 0.5*u*(u + 1)*(u + 2) + 2.0*u*(u + 1) + 9.0*u + 26.0 

The simplified value of the polynomial is:
 0.5*u**3 + 3.5*u**2 + 12.0*u + 26.0 

The value of polynomial at 4 is:
 162.0 

